#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on 2022

@author: aguscarpio99
"""
import argparse
import os

target_program = "arnold_n.py"
#

parser = argparse.ArgumentParser(description='Computes n-period for solutions'+
            ' generated by a model for a (dimK x dimtau) parameter space grid')

parser.add_argument('-ncpus', type=int, nargs=1, default=[1],
                help='Number of child processes'+
                     '\nIt is recommended to use at most the number of '+
                     'available CPU cores')

parser.add_argument('-dimK', type=int, nargs=1, default=[16],
                help='K parameter dimension, corresponding to K-tau plane')

parser.add_argument('-dimtau', type=int, nargs=1, default=[16],
                help='tau parameter dimension, corresponding to K-tau plane')

parser.add_argument('-N_steps', type=int, nargs=1, default=[900000],
                help='Number of steps performed on each simulation'+
                     '\nConsider the program runs a whole simulation for each'
                     ' cell of the grid')

parser.add_argument('-dt', type=float, nargs=1, help='dt', default=[0.00004])

parser.add_argument('-rox', type=float, nargs=1, help='rox', default=[-2.3])

parser.add_argument('-roy', type=float, nargs=1, help='roy', default=[-9])


# TODO:
parser.add_argument('--progressbar', action='store_true',
                help='display progressbar')

args = parser.parse_args()
ncpus = args.ncpus[0]
N_steps = args.N_steps[0]
dt = args.dt[0]
dimK = args.dimK[0]
dimtau = args.dimtau[0]
rox = args.rox[0]
roy = args.roy[0]

if not os.path.isdir(f"/mnt/sda/arnold_maps/results_{rox}_{roy}"):
    os.system(f"mkdir /mnt/sda/arnold_maps/results_{rox}_{roy}")

for arn_number in range(ncpus):
    os.system(f"python3 {target_program} {arn_number} {ncpus}" +
            f" {dimK} {dimtau} {N_steps} {dt} {rox} {roy} &")
